name: Check
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.28.1
      - uses: actions/checkout@v3
      - name: Lint
        run: deno task lint
      - name: Test
        run: deno task test
